name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-24.04
    # steps to run on the job
    steps:
    # checkout the code from the repo
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'true'
    # setup python version
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    # install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root --no-interaction
    # run tests
    - name: Run tests
      run: |
        poetry run pytest tests/